services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 8000
      --reload

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
